apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-jobmanager
  template:
    metadata:
      labels:
        app: flink-jobmanager
    spec:
      containers:
        - name: flink-jobmanager
          image: dmpa3-flink:latest
          imagePullPolicy: IfNotPresent
          args: ["jobmanager"]
          ports:
            - containerPort: 8081
              name: ui
            - containerPort: 6123
              name: rpc
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  selector:
    app: flink-jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: ui
      nodePort: 30081
    - port: 6123
      targetPort: 6123
      name: rpc
  type: NodePort